name: Publish Docker Image

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta cs
        id: meta-cs
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}-cs
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Docker meta cs-renderer
        id: meta-cs-renderer
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}-cs-renderer
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Docker meta phy
        id: meta-phy
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}-phy
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Docker meta phy-renderer
        id: meta-phy-renderer
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}-phy-renderer
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push cs Docker image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-react
          context: .
          push: true
          build-args: |
            BUILD_TARGET=build-cs
          tags: ${{ steps.meta-cs.outputs.tags }}
          labels: ${{ steps.meta-cs.outputs.labels }}
      - name: Build and push cs-renderer Docker image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-react
          context: .
          push: true
          build-args: |
            BUILD_TARGET=build-cs-renderer
          tags: ${{ steps.meta-cs-renderer.outputs.tags }}
          labels: ${{ steps.meta-cs-renderer.outputs.labels }}
      - name: Build and push phy Docker image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-react
          context: .
          push: true
          build-args: |
            BUILD_TARGET=build-phy
          tags: ${{ steps.meta-phy.outputs.tags }}
          labels: ${{ steps.meta-phy.outputs.labels }}
      - name: Build and push phy-renderer Docker image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-react
          context: .
          push: true
          build-args: |
            BUILD_TARGET=build-phy-renderer
          tags: ${{ steps.meta-phy-renderer.outputs.tags }}
          labels: ${{ steps.meta-phy-renderer.outputs.labels }}
